---
title: "Polynomial"
author: "Teo Mendejar"
format: pptx
editor: visual
---

## **What is a Polynomial?**

Polynomial is made up of two terms, namely Poly (meaning "many") and Nominal (meaning "terms."). A polynomial is defined as an expression which is composed of variables, constants and exponents, that are combined using mathematical operations such as addition, subtraction, multiplication and division (No division operation by a variable). Based on the number of terms present in the expression, it is classified as monomial, binomial, and trinomial. Examples of constants, variables and exponents are as follows:

-   Constants. Example: 1, 2, 3, etc.

-   Variables. Example: g, h, x, y, etc.

-   Exponents: Example: 5 in x^5^ etc.

## **Standard Form of a Polynomial**

P(x) = a~n~x^n^ + a~n-1~x^n-1^ +a~n-2~x^n-2^ + ................... + a~1~x + a~0~   

Where a~n~, a~n-1~, a~n-2~, ........................, a~1~, a~0~ are called coefficients of x^n^, x^n-1^, x^n-2^, ....., x and constant term respectively and it should belong to real number (⋲ R).

### **Notation**

The polynomial function is denoted by P(x) where x represents the variable. For example,

P(x) = x^2^-5x+11

If the variable is denoted by a, then the function will be P(a)

## **Degree of a Polynomial**

The [degree of a polynomial](https://byjus.com/maths/degree-of-a-polynomial/) is defined as the highest exponent of a monomial within a polynomial. Thus, a polynomial equation having one variable which has the largest exponent is called a degree of the polynomial.

| Polynomial           | Degree      | Example                       |
|:---------------------|:------------|:------------------------------|
| Zero Polynomial      | Not Defined | 6                             |
| Constant             | 0           | P(x)  = 6                     |
| Linear Polynomial    | 1           | P(x) = 3x+1                   |
| Quadratic Polynomial | 2           | P(x) = 4x^2^+1x+1             |
| Cubic Polynomial     | 3           | P(x) = 6x^3^+4x^2^+3x+1       |
| Quartic Polynomial   | 4           | P(x) = 6x^4^+3x^3^+3x^2^+2x+1 |

**Example:** Find the degree of the polynomial P(x) = 6s^4^+ 3x^2^+ 5x +19

**Solution:**

The degree of the polynomial is 4 as the highest power of the variable 4.

## **Terms of a Polynomial**

The terms of polynomials are the parts of the expression that are generally separated by "+" or "-" signs. So, each part of a polynomial in an expression is a term. For example, in a polynomial, say, 2x^2^ + 5 +4, the number of terms will be 3. The classification of a polynomial is done based on the number of terms in it.

|                        |                        |            |
|------------------------|------------------------|------------|
| **Polynomial**         | **Terms**              | **Degree** |
| P(x) = x^3^-2x^2^+3x+4 | x^3^, -2x^2^, 3x and 4 | 3          |

## **Types of Polynomials**

Depending upon the number of terms, polynomials are divided into the following categories:

-   **Monomial**

-   **Binomial**

-   **Trinomial**

-   **Polynomial containing 4 terms (Quadronomial)**

-   **Polynomial containing 5 terms (pentanomial ) and so on ...**

These polynomials can be combined using addition, subtraction, multiplication, and division but is never divided by a variable. A few examples of **Non Polynomials** are: 1/x+2, x^-3^

### **Monomial**

A monomial is an expression which contains only one term. For an expression to be a monomial, the single term should be a non-zero term. A few examples of monomials are:

-   5x

-   3

-   6a^4^

-   -3xy

### **Binomial**

A binomial is a polynomial expression which contains exactly two terms. A binomial can be considered as a sum or difference between two or more monomials. A few examples of binomials are:

-   -- 5x+3,

-   6a^4^ + 17x

-   xy^2^+xy

### **Trinomial**

A trinomial is an expression which is composed of exactly three terms. A few examples of trinomial expressions are:

-   -- 8a^4^+2x+7

-   4x^2^ + 9x + 7

|                         |                               |                     |
|------------------------|-----------------------------|--------------------|
| **Monomial**            | **Binomial**                  | **Trinomial**       |
| One Term                | Two terms                     | Three terms         |
| Example: x, 3y, 29, x/2 | Example: x^2^+x, x^3^-2x, y+2 | Example: x^2^+2x+20 |

## **Properties**

Some of the important properties of polynomials along with some important polynomial theorems are as follows:

### **Property 1: Division Algorithm**

If a polynomial P(x) is divided by a polynomial G(x) results in quotient Q(x) with remainder R(x), then,

**P(x) = G(x) • Q(x) + R(x)**

Where R(x)=0 or the degree of R(x) \< the degree of G(x)

### **Property 2: Bezout's Theorem**

Polynomial P(x) is divisible by binomial (x -- a) if and only if **P(a) = 0**.

### **Property 3: Remainder Theorem**

If P(x) is divided by (x -- a) with remainder r, then **P(a) = r**.

### **Property 4: Factor Theorem**

A polynomial P(x) divided by Q(x) results in R(x) with zero remainders if and only if Q(x) is a factor of P(x).

**Learn More:** [Factor Theorem](https://byjus.com/maths/factor-theorem/)

### **Property 5: Intermediate Value Theorem**

If P(x) is a polynomial, and P(x) ≠ P(y) for (x \< y), then P(x) takes every value from P(x) to P(y) in the closed interval \[x, y\].

**Learn More:** [Intermediate Value Theorem](https://byjus.com/maths/intermediate-value-theorem/)

### **Property 6**

The addition, subtraction and multiplication of polynomials P and Q result in a polynomial where,

**Degree(P ± Q) ≤ Degree(P or Q)**

**Degree(P × Q) = Degree(P) + Degree(Q)**

### **Property 7**

If a polynomial P is divisible by a polynomial Q, then every zero of Q is also a zero of P.

### **Property 8**

If a polynomial P is divisible by two co-prime polynomials Q and R, then it is divisible by (Q • R).

### **Property 9**

If P(x) = a~0~ + a~1~x + a~2~x^2^ + ...... + a~n~x^n^ is a polynomial such that deg(P) = n ≥ 0 then, P has at most "n" distinct roots.

### **Property 10: Descartes' Rule of Sign**

The number of positive real zeroes in a polynomial function P(x) is the same or less than by an even number as the number of changes in the sign of the coefficients. So, if there are "K" sign changes, the number of roots will be "k" or "(k -- a)", where "a" is some even number.

### **Property 11: Fundamental Theorem of Algebra**

Every non-constant single-variable polynomial with complex coefficients has at least one complex zero.

### **Property 12**

If P(x) is a polynomial with real coefficients and has one complex zero (x = a -- bi), then x = a + bi will also be a zero of P(x). Also, x^2^ -- 2ax + a^2^ + b^2^ will be a factor of P(x).

## **Polynomial Equations**

Polynomial equations are those expressions which are made up of multiple constants and variables. The standard form of writing a [polynomial equation](https://byjus.com/maths/polynomial-equations/) is to put the highest degree first and then, at last, the constant term. An example of a polynomial equation is:

0 = a^4^ +3a^3^ -2a^2^ +a +1

## **Polynomial Functions**

A [polynomial function](https://byjus.com/maths/polynomial-functions/) is an expression constructed with one or more terms of variables with constant exponents. If there are real numbers denoted by a, then function with one variable and of degree n can be written as:

|                                                                                     |
|------------------------------------------------------------------------|
| **f(x) = a~0~x^n^ + a~1~x^n-1^ + a~2~x^n-2^ + ..... + a~n-2~x^2^ + a~n-1~x + a~n~** |

## **Solving Polynomials**

Any polynomial can be easily solved using basic algebra and factorization concepts. While solving the polynomial equation, the first step is to set the right-hand side as 0. The explanation of a polynomial solution is explained in two different ways:

-   Solving Linear Polynomials

-   Solving Quadratic Polynomials

### **Solving Linear Polynomials**

Getting the solution of linear polynomials is easy and simple. First, isolate the variable term and make the equation as equal to zero. Then solve as basic algebra operation. An example of finding the solution of a linear equation is given below:

**Example:** Solve 3x -- 9

**Solution:**

First, make the equation as 0. So,

3x -- 9 = 0

⇒ 3x = 9

⇒ x = 9/3

Or, x = 3.

Thus, the solution of 3x-9 is x = 3.

### **Solving Quadratic Polynomials**

To solve a quadratic polynomial, first, rewrite the expression in the descending order of degree. Then, equate the equation and perform [polynomial factorization](https://byjus.com/maths/factorization-of-polynomials/) to get the solution of the equation. An example to find the solution of a quadratic polynomial is given below for better understanding.

**Example:** Solve 3x^2^ -- 6x + x^3^ -- 18

**Solution:**

First, arrange the polynomial in the descending order of degree and equate to zero.

⇒ x^3^ + 3x^2^ -6x -- 18 = 0

Now, take the common terms.

x^2^(x+3) -- 6(x+3) =0

⇒ (x^2^-6)(x+3)=0

So, the solutions will be x =-3 or

x^2^ = 6

Or, x = ±√6

**More Polynomials Related Resources:**

|                                                                                                 |                                                                         |
|-----------------------------------------|-------------------------------|
| [Remainder Theorem And Polynomials](https://byjus.com/maths/remainder-theorem-and-polynomials/) | [Algebraic Expressions](https://byjus.com/maths/algebraic-expressions/) |
| [Polynomials Worksheets](https://byjus.com/maths/polynomials-worksheets/)                       | [Zeros Of polynomial](https://byjus.com/maths/zeros-of-polynomial/)     |

## **Polynomial Operations**

There are four main polynomial operations which are:

-   Addition of Polynomials

-   Subtraction of Polynomials

-   Multiplication of Polynomials

-   Division of Polynomials

Each of the operations on polynomials is explained below using solved examples.

### **Addition of Polynomials**

To add polynomials, always add the like terms, i.e. the terms having the same variable and power. The addition of polynomials always results in a polynomial of the same degree. For example,

**Example:** Find the sum of two polynomials: 5x^3^+3x^2^y+4xy−6y^2^, 3x^2^+7x^2^y−2xy+4xy^2^−5

**Solution:**

First, combine the like terms while leaving the unlike terms as they are. Hence,

(5x^3^+3x^2^y+4xy−6y^2^)+(3x^2^+7x^2^y−2xy+4xy^2^−5)

= 5x^3^+3x^2^+(3+7)x^2^y+(4−2)xy+4xy^2^−6y^2^−5

= 5x^3^+3x^2^+10x^2^y+2xy+4xy^2^−6y^2^−5

### **Subtraction of Polynomials**

Subtracting polynomials is similar to addition, the only difference being the type of operation. So, subtract the like terms to obtain the solution. It should be noted that subtraction of polynomials also results in a polynomial of the same degree.

**Example:** Find the difference of two polynomials: 5x^3^+3x^2^y+4xy−6y^2^, 3x^2^+7x^2^y−2xy+4xy^2^−5

**Solution:**

First, combine the like terms while leaving the unlike terms as they are. Hence,

(5x^3^+3x^2^y+4xy−6y^2^)-(3x^2^+7x^2^y−2xy+4xy^2^−5)

= 5x^3^-3x^2^+(3-7)x^2^y+(4+2)xy-4xy^2^−6y^2^+5

= 5x^3^-3x^2^-4x^2^y+6xy-4xy^2^−6y^2^+5

### **Multiplication of Polynomials**

Two or more polynomial when multiplied always result in a polynomial of higher degree (unless one of them is a constant polynomial). An example of [multiplying polynomials](https://byjus.com/maths/multiplying-polynomials/) is given below:

**Example:** Solve (6x−3y)×(2x+5y)

**Solution:**

⇒ 6x ×(2x+5y)--3y × (2x+5y) ---------- Using distributive law of multiplication

⇒ (12x^2^+30xy) -- (6yx+15y^2^) ---------- Using distributive law of multiplication

⇒12x^2^+30xy--6xy--15y^2^ ----------------- as xy = yx

Thus, (6x−3y)×(2x+5y)=12x^2^+24xy−15y^2^

### **Division of Polynomials**

Division of two polynomial may or may not result in a polynomial. Let us study below the division of polynomials in detail. To divide polynomials, follow the given steps:

**Polynomial Division Steps:**

If a polynomial has more than one term, we use long division method for the same. Following are the steps for it.

1.  Write the polynomial in descending order.

2.  Check the highest power and divide the terms by the same.

3.  Use the answer in step 2 as the division symbol.

4.  Now subtract it and bring down the next term.

5.  Repeat steps 2 to 4 until you have no more terms to carry down.

6.  Note the final answer, including remainder, will be in the fraction form (last subtract term).

## **Polynomial Examples**

**Example:**

Given two polynomial 7s^3^+2s^2^+3s+9 and 5s^2^+2s+1.

Solve these using mathematical operation.

**Solution:**

**Given polynomial:**

7s^3^+2s^2^+3s+9 and 5s^2^+2s+1

**Polynomial Addition:** (7s^3^+2s^2^+3s+9) + (5s^2^+2s+1)

= 7s^3^+(2s^2^+5s^2^)+(3s+2s)+(9+1)

= 7s^3^+7s^2^+5s+10

Hence, addition result in a polynomial.

**Polynomial Subtraction:** (7s^3^+2s^2^+3s+9) -- (5s^2^+2s+1)

= 7s^3^+(2s^2^-5s^2^)+(3s-2s)+(9-1)

= 7s^3^-3s^2^+s+8

Hence addition result in a polynomial.

**Polynomial Multiplication:**(7s^3^+2s^2^+3s+9) × (5s^2^+2s+1)

= 7s^3^ (5s^2^+2s+1)+2s^2^ (5s^2^+2s+1)+3s (5s^2^+2s+1)+9 (5s^2^+2s+1))

= (35s^5^+14s^4^+7s^3^)+ (10s^4^+4s^3^+2s^2^)+ (15s^3^+6s^2^+3s)+(45s^2^+18s+9)

= 35s^5^+(14s^4^+10s^4^)+(7s^3^+4s^3^+15s^3^)+ (2s^2^+6s^2^+45s^2^)+ (3s+18s)+9

= 35s^5^+24s^4^+26s^3^+ 53s^2^+ 21s +9

**Polynomial Division: (**7s^3^+2s^2^+3s+9) ÷ (5s^2^+2s+1)

(7s^3^+2s^2^+3s+9)/(5s^2^+2s+1)

This cannot be simplified. Therefore, division of these polynomial do not result in a Polynomial.

Keep visiting BYJU'S to get more such math lessons on different topics. Also, register now to access numerous video lessons for different math concepts to learn in a more effective and engaging way.\

## **Frequently Asked Questions -- FAQs**

Q1

### **What is a Polynomial?**

A polynomial is an expression that consists of variables (or indeterminate), terms, exponents and constants. For example, 3x^2^ -2x-10 is a polynomial.

Q2

### **What are terms, degrees and exponents in a polynomial?**

If 2x^2^ -- 3x +19 is a polynomial, then;\
Terms: 2x^2^,-3x & 19\
Degree: 2 (the highest exponent of variable x)\
Exponents: Power raised to variable x, i.e. 2 and 1.

Q3

### **What is the standard form of the polynomial?**

A standard polynomial is the one where the highest degree is the first term, and subsequently, the other terms come. For example, x^3^ -- 3x^2^ + x -12 is a standard polynomial. So the highest degree here is 3, then comes 2 and then 1.

Q4

### **What is the degree of zero and constant polynomial?**

The degree of zero polynomial is not defined while the degree of a constant polynomial is 1.

Q5

### **Is 8 a polynomial?**

8 can be written as 8x^0^ or 0x^2^+0x+8, which represents the polynomial expression. Therefore, we can consider 8 as a polynomial.

Q6

### **How to add and subtract polynomials?**

To add polynomials, always add the like terms, i.e. the terms having the same variable and power. The addition of polynomials always results in a polynomial of the same degree.\
For example if we add x^2^+3x and 2x^2^ + 2x + 9, then we get:\
x^2^+3x+2x^2^+2x+9 = 3x^2^+5x+9. Subtracting polynomials is similar to addition, the only difference being the type of operation. So, subtract the like terms to obtain the solution. It should be noted that subtraction of polynomials also results in a polynomial of the same degree.\
So,\
x^2^+3x-(2x^2^+2x+9) = x^2^+3x-2x^2^-2x-9 = -x^2^+x-9
